/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

/**
 *
 * @author LAB7-PC6-USER
 */
public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
        this.setExtendedState(FrmAdministrador.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmLoggin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiRegistrar = new javax.swing.JMenuItem();
        jmiEditar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jmiDateUtil = new javax.swing.JMenuItem();
        jmiCalendar = new javax.swing.JMenuItem();
        jmiTime = new javax.swing.JMenuItem();
        jmiDateSql = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMINISTRADOR");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmSalir);

        jmLoggin.setText("Loggin");
        jmLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLogginActionPerformed(evt);
            }
        });
        jMenu1.add(jmLoggin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios");

        jmiRegistrar.setText("Registrar");
        jmiRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRegistrar);

        jmiEditar.setText("Editar");
        jmiEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiEditar);

        jmiEliminar.setText("Eliminar");
        jMenu2.add(jmiEliminar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ayuda");

        jmiDateUtil.setText("Date.util");
        jmiDateUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDateUtilActionPerformed(evt);
            }
        });
        jMenu5.add(jmiDateUtil);

        jmiCalendar.setText("Calendar");
        jmiCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCalendarActionPerformed(evt);
            }
        });
        jMenu5.add(jmiCalendar);

        jmiTime.setText("Time");
        jmiTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimeActionPerformed(evt);
            }
        });
        jMenu5.add(jmiTime);

        jmiDateSql.setText("Date.sql");
        jmiDateSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDateSqlActionPerformed(evt);
            }
        });
        jMenu5.add(jmiDateSql);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(238, Short.MAX_VALUE))
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLogginActionPerformed
        Loggin loggin = new Loggin();
        loggin.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jmLogginActionPerformed

    private void jmiRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmIRegistro frmIRegistro = new FrmIRegistro();
        escritorio.add(frmIRegistro);
        frmIRegistro.setVisible(true);
        frmIRegistro.toFront();
        try {
            frmIRegistro.setMaximum(true);
            frmIRegistro.setMaximizable(true);
            frmIRegistro.setSelected(true);
        } catch (Exception e) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jmiRegistrarActionPerformed

    private void jmiEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmIEditar frmIEditar = new FrmIEditar();
        escritorio.add(frmIEditar);
        frmIEditar.setVisible(true);
        frmIEditar.toFront();
        try {
            frmIEditar.setMaximum(true);
            frmIEditar.setMaximizable(true);
            frmIEditar.setSelected(true);
        } catch (Exception e) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jmiEditarActionPerformed

    private void jmiDateUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDateUtilActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmIDateUtil frmIDateUtil = new FrmIDateUtil();
        escritorio.add(frmIDateUtil);
        frmIDateUtil.setVisible(true);
        try {
            frmIDateUtil.setMaximum(true);
            frmIDateUtil.setMaximizable(true);
        } catch (Exception e) {
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_jmiDateUtilActionPerformed

    private void jmiCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCalendarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmICalendar frmICalendar = new FrmICalendar();
        escritorio.add(frmICalendar);
        frmICalendar.setVisible(true);
        try {
            frmICalendar.setMaximum(true);
            frmICalendar.setMaximizable(true);
        } catch (Exception e) {
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jmiCalendarActionPerformed

    private void jmiTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimeActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmITime frmITime = new FrmITime();
        escritorio.add(frmITime);
        frmITime.setVisible(true);
        try {
            frmITime.setMaximum(true);
            frmITime.setMaximizable(true);
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jmiTimeActionPerformed

    private void jmiDateSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDateSqlActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FrmIDateSQL frmIDateSQL = new FrmIDateSQL();
        escritorio.add(frmIDateSQL);
        frmIDateSQL.setVisible(true);
        try {
            frmIDateSQL.setMaximum(true);
            frmIDateSQL.setMaximizable(true);
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jmiDateSqlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmLoggin;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmiCalendar;
    private javax.swing.JMenuItem jmiDateSql;
    private javax.swing.JMenuItem jmiDateUtil;
    private javax.swing.JMenuItem jmiEditar;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiRegistrar;
    private javax.swing.JMenuItem jmiTime;
    // End of variables declaration//GEN-END:variables
}
