/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB7-PC6-USER
 */
public class FrmIEjemplos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIEjemplos
     */
    public FrmIEjemplos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSinFormato = new javax.swing.JButton();
        btnConFormato = new javax.swing.JButton();

        btnSinFormato.setText("Date sin formato");
        btnSinFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinFormatoActionPerformed(evt);
            }
        });

        btnConFormato.setText("Date con formato");
        btnConFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConFormato)
                    .addComponent(btnSinFormato))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnSinFormato)
                .addGap(18, 18, 18)
                .addComponent(btnConFormato)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSinFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinFormatoActionPerformed
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        JOptionPane.showMessageDialog(null, formato.format(fecha));
        //JOptionPane.showMessageDialog(null, fecha.getTime());
// TODO add your handling code here:
    }//GEN-LAST:event_btnSinFormatoActionPerformed

    private void btnConFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConFormatoActionPerformed
        java.sql.Date fecha = new java.sql.Date(WIDTH);
        JOptionPane.showMessageDialog(null, fecha.getTime());
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnConFormatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConFormato;
    private javax.swing.JButton btnSinFormato;
    // End of variables declaration//GEN-END:variables
}
