/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

/**
 *
 * @author LAB7-PC6-USER
 */
public class FrmIDateUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIDateUtil
     */
    public FrmIDateUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoria = new javax.swing.JRadioButton();
        rbtEjemplos = new javax.swing.JRadioButton();
        rbtPractica = new javax.swing.JRadioButton();
        escritorio2 = new javax.swing.JDesktopPane();

        jLabel1.setText("DateUtil");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        rbtGrupo1.add(rbtTeoria);
        rbtTeoria.setText("Teoria");
        rbtTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtEjemplos);
        rbtEjemplos.setText("Ejemplos");
        rbtEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemplosActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtPractica);
        rbtPractica.setText("Práctica");
        rbtPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtPractica)
                    .addComponent(rbtEjemplos)
                    .addComponent(rbtTeoria))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtTeoria)
                .addGap(18, 18, 18)
                .addComponent(rbtEjemplos)
                .addGap(18, 18, 18)
                .addComponent(rbtPractica)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout escritorio2Layout = new javax.swing.GroupLayout(escritorio2);
        escritorio2.setLayout(escritorio2Layout);
        escritorio2Layout.setHorizontalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorio2Layout.setVerticalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(escritorio2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritorio2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPracticaActionPerformed

    private void rbtTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaActionPerformed
        escritorio2.removeAll();
        escritorio2.repaint();
        FrmITeoria frmITeoria = new FrmITeoria();
        escritorio2.add(frmITeoria);
        frmITeoria.setVisible(true);
        try {
            frmITeoria.setMaximum(true);
            frmITeoria.setMaximizable(true);
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rbtTeoriaActionPerformed

    private void rbtEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemplosActionPerformed
        escritorio2.removeAll();
        escritorio2.repaint();
        FrmIEjemplos frmIEjemplos = new FrmIEjemplos();
        escritorio2.add(frmIEjemplos);
        frmIEjemplos.setVisible(true);
        try {
            frmIEjemplos.setMaximum(true);
            frmIEjemplos.setMaximizable(true);
        } catch (Exception e) {
        }            // TODO add your handling code here:
    }//GEN-LAST:event_rbtEjemplosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtEjemplos;
    private javax.swing.ButtonGroup rbtGrupo1;
    private javax.swing.JRadioButton rbtPractica;
    private javax.swing.JRadioButton rbtTeoria;
    // End of variables declaration//GEN-END:variables
}
